// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    NoteCom: typeof import('./../src/components/noteCom/index.vue')['default']
    TaskCom: typeof import('./../src/components/taskCom/index.vue')['default']
    TaskItem: typeof import('./../src/components/taskCom/components/taskItem.vue')['default']
  }
}

export { }
